#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 110
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 35
#define ALIAS_COUNT 0
#define TOKEN_COUNT 18
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 3

enum {
  anon_sym_SEMI = 1,
  aux_sym__new_line_token1 = 2,
  sym_bare_word = 3,
  anon_sym_DQUOTE = 4,
  aux_sym__double_quotes_internal_token1 = 5,
  anon_sym_LBRACE = 6,
  anon_sym_RBRACE = 7,
  aux_sym__braces_internal_token1 = 8,
  anon_sym_LBRACK = 9,
  anon_sym_RBRACK = 10,
  anon_sym_DOLLAR = 11,
  anon_sym_LPAREN = 12,
  anon_sym_RPAREN = 13,
  sym_alowed_variable_name = 14,
  anon_sym_BSLASH = 15,
  aux_sym__backslash_substitution_token1 = 16,
  aux_sym_comment_token1 = 17,
  sym_tcl_script = 18,
  sym_command = 19,
  sym_arguments_list = 20,
  sym__terminator = 21,
  sym__new_line = 22,
  sym__word = 23,
  sym_double_quotes = 24,
  aux_sym__double_quotes_internal = 25,
  sym_braces = 26,
  aux_sym__braces_internal = 27,
  sym__even_braces = 28,
  sym_command_substitution = 29,
  sym_variable_substitution = 30,
  sym__backslash_substitution = 31,
  sym_comment = 32,
  aux_sym_tcl_script_repeat1 = 33,
  aux_sym_arguments_list_repeat1 = 34,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SEMI] = ";",
  [aux_sym__new_line_token1] = "_new_line_token1",
  [sym_bare_word] = "bare_word",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym__double_quotes_internal_token1] = "_double_quotes_internal_token1",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [aux_sym__braces_internal_token1] = "_braces_internal_token1",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_DOLLAR] = "$",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_alowed_variable_name] = "alowed_variable_name",
  [anon_sym_BSLASH] = "\\",
  [aux_sym__backslash_substitution_token1] = "_backslash_substitution_token1",
  [aux_sym_comment_token1] = "comment_token1",
  [sym_tcl_script] = "tcl_script",
  [sym_command] = "command",
  [sym_arguments_list] = "arguments_list",
  [sym__terminator] = "_terminator",
  [sym__new_line] = "_new_line",
  [sym__word] = "_word",
  [sym_double_quotes] = "double_quotes",
  [aux_sym__double_quotes_internal] = "_double_quotes_internal",
  [sym_braces] = "braces",
  [aux_sym__braces_internal] = "_braces_internal",
  [sym__even_braces] = "_even_braces",
  [sym_command_substitution] = "command_substitution",
  [sym_variable_substitution] = "variable_substitution",
  [sym__backslash_substitution] = "_backslash_substitution",
  [sym_comment] = "comment",
  [aux_sym_tcl_script_repeat1] = "tcl_script_repeat1",
  [aux_sym_arguments_list_repeat1] = "arguments_list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [aux_sym__new_line_token1] = aux_sym__new_line_token1,
  [sym_bare_word] = sym_bare_word,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym__double_quotes_internal_token1] = aux_sym__double_quotes_internal_token1,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [aux_sym__braces_internal_token1] = aux_sym__braces_internal_token1,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_alowed_variable_name] = sym_alowed_variable_name,
  [anon_sym_BSLASH] = anon_sym_BSLASH,
  [aux_sym__backslash_substitution_token1] = aux_sym__backslash_substitution_token1,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [sym_tcl_script] = sym_tcl_script,
  [sym_command] = sym_command,
  [sym_arguments_list] = sym_arguments_list,
  [sym__terminator] = sym__terminator,
  [sym__new_line] = sym__new_line,
  [sym__word] = sym__word,
  [sym_double_quotes] = sym_double_quotes,
  [aux_sym__double_quotes_internal] = aux_sym__double_quotes_internal,
  [sym_braces] = sym_braces,
  [aux_sym__braces_internal] = aux_sym__braces_internal,
  [sym__even_braces] = sym__even_braces,
  [sym_command_substitution] = sym_command_substitution,
  [sym_variable_substitution] = sym_variable_substitution,
  [sym__backslash_substitution] = sym__backslash_substitution,
  [sym_comment] = sym_comment,
  [aux_sym_tcl_script_repeat1] = aux_sym_tcl_script_repeat1,
  [aux_sym_arguments_list_repeat1] = aux_sym_arguments_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__new_line_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_bare_word] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__double_quotes_internal_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__braces_internal_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_alowed_variable_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__backslash_substitution_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_tcl_script] = {
    .visible = true,
    .named = true,
  },
  [sym_command] = {
    .visible = true,
    .named = true,
  },
  [sym_arguments_list] = {
    .visible = true,
    .named = true,
  },
  [sym__terminator] = {
    .visible = false,
    .named = true,
  },
  [sym__new_line] = {
    .visible = false,
    .named = true,
  },
  [sym__word] = {
    .visible = false,
    .named = true,
  },
  [sym_double_quotes] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__double_quotes_internal] = {
    .visible = false,
    .named = false,
  },
  [sym_braces] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__braces_internal] = {
    .visible = false,
    .named = false,
  },
  [sym__even_braces] = {
    .visible = false,
    .named = true,
  },
  [sym_command_substitution] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_substitution] = {
    .visible = true,
    .named = true,
  },
  [sym__backslash_substitution] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_tcl_script_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_arguments_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_arg_list = 1,
  field_name = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_arg_list] = "arg_list",
  [field_name] = "name",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
  [1] =
    {field_arg_list, 1},
    {field_name, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 3,
  [6] = 6,
  [7] = 7,
  [8] = 7,
  [9] = 6,
  [10] = 3,
  [11] = 6,
  [12] = 7,
  [13] = 13,
  [14] = 13,
  [15] = 13,
  [16] = 13,
  [17] = 13,
  [18] = 18,
  [19] = 18,
  [20] = 18,
  [21] = 18,
  [22] = 18,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 23,
  [27] = 24,
  [28] = 23,
  [29] = 29,
  [30] = 24,
  [31] = 23,
  [32] = 24,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 25,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 33,
  [42] = 34,
  [43] = 38,
  [44] = 36,
  [45] = 40,
  [46] = 25,
  [47] = 35,
  [48] = 39,
  [49] = 49,
  [50] = 38,
  [51] = 25,
  [52] = 34,
  [53] = 40,
  [54] = 33,
  [55] = 36,
  [56] = 35,
  [57] = 39,
  [58] = 34,
  [59] = 59,
  [60] = 36,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 38,
  [65] = 65,
  [66] = 66,
  [67] = 63,
  [68] = 63,
  [69] = 35,
  [70] = 61,
  [71] = 63,
  [72] = 61,
  [73] = 63,
  [74] = 74,
  [75] = 61,
  [76] = 76,
  [77] = 61,
  [78] = 33,
  [79] = 79,
  [80] = 80,
  [81] = 80,
  [82] = 80,
  [83] = 83,
  [84] = 80,
  [85] = 85,
  [86] = 80,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 25,
  [91] = 91,
  [92] = 34,
  [93] = 91,
  [94] = 38,
  [95] = 91,
  [96] = 96,
  [97] = 96,
  [98] = 96,
  [99] = 36,
  [100] = 91,
  [101] = 96,
  [102] = 91,
  [103] = 96,
  [104] = 33,
  [105] = 40,
  [106] = 39,
  [107] = 107,
  [108] = 35,
  [109] = 87,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(12);
      if (lookahead == '"') ADVANCE(19);
      if (lookahead == '#') ADVANCE(39);
      if (lookahead == '$') ADVANCE(30);
      if (lookahead == '(') ADVANCE(31);
      if (lookahead == ')') ADVANCE(34);
      if (lookahead == ';') ADVANCE(13);
      if (lookahead == '[') ADVANCE(27);
      if (lookahead == '\\') ADVANCE(36);
      if (lookahead == ']') ADVANCE(28);
      if (lookahead == '{') ADVANCE(23);
      if (lookahead == '}') ADVANCE(24);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(38);
      if (lookahead != 0) ADVANCE(37);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(19);
      if (lookahead == '$') ADVANCE(30);
      if (lookahead == '(') ADVANCE(32);
      if (lookahead == '[') ADVANCE(27);
      if (lookahead == ']') ADVANCE(29);
      if (lookahead == '{') ADVANCE(23);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      if (lookahead != 0) ADVANCE(18);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(19);
      if (lookahead == '$') ADVANCE(30);
      if (lookahead == '(') ADVANCE(33);
      if (lookahead == '[') ADVANCE(27);
      if (lookahead == '\\') ADVANCE(36);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(20);
      if (lookahead != 0) ADVANCE(22);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(19);
      if (lookahead == '$') ADVANCE(30);
      if (lookahead == '[') ADVANCE(27);
      if (lookahead == '\\') ADVANCE(36);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0) ADVANCE(22);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(19);
      if (lookahead == '$') ADVANCE(30);
      if (lookahead == '[') ADVANCE(27);
      if (lookahead == ']') ADVANCE(29);
      if (lookahead == '{') ADVANCE(23);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(5)
      if (lookahead != 0) ADVANCE(18);
      END_STATE();
    case 6:
      if (lookahead == '"') ADVANCE(19);
      if (lookahead == '$') ADVANCE(30);
      if (lookahead == '[') ADVANCE(27);
      if (lookahead == '{') ADVANCE(23);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(6)
      if (lookahead != 0) ADVANCE(18);
      END_STATE();
    case 7:
      if (lookahead == '{') ADVANCE(23);
      if (lookahead == '}') ADVANCE(24);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0) ADVANCE(26);
      END_STATE();
    case 8:
      if (eof) ADVANCE(12);
      if (lookahead == '\n') ADVANCE(15);
      if (lookahead == '"') ADVANCE(19);
      if (lookahead == '$') ADVANCE(30);
      if (lookahead == '(') ADVANCE(32);
      if (lookahead == ';') ADVANCE(14);
      if (lookahead == '[') ADVANCE(27);
      if (lookahead == '{') ADVANCE(23);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(8)
      if (lookahead != 0) ADVANCE(18);
      END_STATE();
    case 9:
      if (eof) ADVANCE(12);
      if (lookahead == '\n') ADVANCE(15);
      if (lookahead == '"') ADVANCE(19);
      if (lookahead == '$') ADVANCE(30);
      if (lookahead == ';') ADVANCE(14);
      if (lookahead == '[') ADVANCE(27);
      if (lookahead == '{') ADVANCE(23);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(9)
      if (lookahead != 0) ADVANCE(18);
      END_STATE();
    case 10:
      if (eof) ADVANCE(12);
      if (lookahead == '\n') ADVANCE(15);
      if (lookahead == ';') ADVANCE(13);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(10)
      END_STATE();
    case 11:
      if (eof) ADVANCE(12);
      if (lookahead == '"') ADVANCE(19);
      if (lookahead == '#') ADVANCE(17);
      if (lookahead == '$') ADVANCE(30);
      if (lookahead == '[') ADVANCE(27);
      if (lookahead == '{') ADVANCE(23);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(11)
      if (lookahead != 0) ADVANCE(18);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_SEMI);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '$' &&
          lookahead != '[' &&
          lookahead != '{') ADVANCE(18);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym__new_line_token1);
      if (lookahead == '\n') ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym__new_line_token1);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(38);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_bare_word);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ' ||
          lookahead == '"' ||
          lookahead == '$' ||
          lookahead == '[' ||
          lookahead == '{') ADVANCE(39);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_bare_word);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '$' &&
          lookahead != '[' &&
          lookahead != '{') ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym__double_quotes_internal_token1);
      if (lookahead == '(') ADVANCE(33);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '$' &&
          lookahead != '[' &&
          lookahead != '\\') ADVANCE(22);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym__double_quotes_internal_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '$' &&
          lookahead != '[' &&
          lookahead != '\\') ADVANCE(22);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym__double_quotes_internal_token1);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '$' &&
          lookahead != '[' &&
          lookahead != '\\') ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym__braces_internal_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(26);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym__braces_internal_token1);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '$' &&
          lookahead != '[' &&
          lookahead != '{') ADVANCE(18);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '$' &&
          lookahead != '[' &&
          lookahead != '{') ADVANCE(18);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '$' &&
          lookahead != '[' &&
          lookahead != '\\') ADVANCE(22);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_alowed_variable_name);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym__backslash_substitution_token1);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym__backslash_substitution_token1);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(38);
      if (lookahead != 0) ADVANCE(37);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(39);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 11},
  [2] = {.lex_state = 11},
  [3] = {.lex_state = 9},
  [4] = {.lex_state = 11},
  [5] = {.lex_state = 9},
  [6] = {.lex_state = 9},
  [7] = {.lex_state = 9},
  [8] = {.lex_state = 9},
  [9] = {.lex_state = 9},
  [10] = {.lex_state = 5},
  [11] = {.lex_state = 5},
  [12] = {.lex_state = 5},
  [13] = {.lex_state = 6},
  [14] = {.lex_state = 6},
  [15] = {.lex_state = 6},
  [16] = {.lex_state = 6},
  [17] = {.lex_state = 6},
  [18] = {.lex_state = 6},
  [19] = {.lex_state = 6},
  [20] = {.lex_state = 6},
  [21] = {.lex_state = 6},
  [22] = {.lex_state = 6},
  [23] = {.lex_state = 4},
  [24] = {.lex_state = 4},
  [25] = {.lex_state = 8},
  [26] = {.lex_state = 4},
  [27] = {.lex_state = 4},
  [28] = {.lex_state = 4},
  [29] = {.lex_state = 4},
  [30] = {.lex_state = 4},
  [31] = {.lex_state = 4},
  [32] = {.lex_state = 4},
  [33] = {.lex_state = 9},
  [34] = {.lex_state = 9},
  [35] = {.lex_state = 9},
  [36] = {.lex_state = 9},
  [37] = {.lex_state = 8},
  [38] = {.lex_state = 9},
  [39] = {.lex_state = 9},
  [40] = {.lex_state = 9},
  [41] = {.lex_state = 9},
  [42] = {.lex_state = 9},
  [43] = {.lex_state = 9},
  [44] = {.lex_state = 9},
  [45] = {.lex_state = 9},
  [46] = {.lex_state = 2},
  [47] = {.lex_state = 9},
  [48] = {.lex_state = 9},
  [49] = {.lex_state = 11},
  [50] = {.lex_state = 5},
  [51] = {.lex_state = 3},
  [52] = {.lex_state = 5},
  [53] = {.lex_state = 5},
  [54] = {.lex_state = 5},
  [55] = {.lex_state = 5},
  [56] = {.lex_state = 5},
  [57] = {.lex_state = 5},
  [58] = {.lex_state = 4},
  [59] = {.lex_state = 7},
  [60] = {.lex_state = 4},
  [61] = {.lex_state = 7},
  [62] = {.lex_state = 10},
  [63] = {.lex_state = 7},
  [64] = {.lex_state = 4},
  [65] = {.lex_state = 4},
  [66] = {.lex_state = 7},
  [67] = {.lex_state = 7},
  [68] = {.lex_state = 7},
  [69] = {.lex_state = 4},
  [70] = {.lex_state = 7},
  [71] = {.lex_state = 7},
  [72] = {.lex_state = 7},
  [73] = {.lex_state = 7},
  [74] = {.lex_state = 10},
  [75] = {.lex_state = 7},
  [76] = {.lex_state = 7},
  [77] = {.lex_state = 7},
  [78] = {.lex_state = 4},
  [79] = {.lex_state = 10},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 7},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 7},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 10},
  [88] = {.lex_state = 10},
  [89] = {.lex_state = 1},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_alowed_variable_name] = ACTIONS(1),
    [anon_sym_BSLASH] = ACTIONS(1),
    [aux_sym_comment_token1] = ACTIONS(1),
  },
  [1] = {
    [sym_tcl_script] = STATE(107),
    [sym_command] = STATE(62),
    [sym__word] = STATE(3),
    [sym_double_quotes] = STATE(3),
    [sym_braces] = STATE(3),
    [sym_command_substitution] = STATE(3),
    [sym_variable_substitution] = STATE(3),
    [sym_comment] = STATE(79),
    [aux_sym_tcl_script_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_bare_word] = ACTIONS(5),
    [anon_sym_DQUOTE] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_DOLLAR] = ACTIONS(13),
    [aux_sym_comment_token1] = ACTIONS(15),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    ACTIONS(19), 1,
      sym_bare_word,
    ACTIONS(22), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_LBRACE,
    ACTIONS(28), 1,
      anon_sym_LBRACK,
    ACTIONS(31), 1,
      anon_sym_DOLLAR,
    ACTIONS(34), 1,
      aux_sym_comment_token1,
    STATE(2), 1,
      aux_sym_tcl_script_repeat1,
    STATE(79), 2,
      sym_command,
      sym_comment,
    STATE(5), 5,
      sym__word,
      sym_double_quotes,
      sym_braces,
      sym_command_substitution,
      sym_variable_substitution,
  [36] = 9,
    ACTIONS(39), 1,
      anon_sym_SEMI,
    ACTIONS(41), 1,
      sym_bare_word,
    ACTIONS(43), 1,
      anon_sym_DQUOTE,
    ACTIONS(45), 1,
      anon_sym_LBRACE,
    ACTIONS(47), 1,
      anon_sym_LBRACK,
    ACTIONS(49), 1,
      anon_sym_DOLLAR,
    STATE(87), 1,
      sym_arguments_list,
    ACTIONS(37), 2,
      ts_builtin_sym_end,
      aux_sym__new_line_token1,
    STATE(7), 6,
      sym__word,
      sym_double_quotes,
      sym_braces,
      sym_command_substitution,
      sym_variable_substitution,
      aux_sym_arguments_list_repeat1,
  [70] = 11,
    ACTIONS(5), 1,
      sym_bare_word,
    ACTIONS(7), 1,
      anon_sym_DQUOTE,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      anon_sym_DOLLAR,
    ACTIONS(15), 1,
      aux_sym_comment_token1,
    ACTIONS(51), 1,
      ts_builtin_sym_end,
    STATE(2), 1,
      aux_sym_tcl_script_repeat1,
    STATE(74), 1,
      sym_command,
    STATE(79), 1,
      sym_comment,
    STATE(3), 5,
      sym__word,
      sym_double_quotes,
      sym_braces,
      sym_command_substitution,
      sym_variable_substitution,
  [108] = 9,
    ACTIONS(37), 1,
      aux_sym__new_line_token1,
    ACTIONS(39), 1,
      anon_sym_SEMI,
    ACTIONS(53), 1,
      sym_bare_word,
    ACTIONS(55), 1,
      anon_sym_DQUOTE,
    ACTIONS(57), 1,
      anon_sym_LBRACE,
    ACTIONS(59), 1,
      anon_sym_LBRACK,
    ACTIONS(61), 1,
      anon_sym_DOLLAR,
    STATE(87), 1,
      sym_arguments_list,
    STATE(8), 6,
      sym__word,
      sym_double_quotes,
      sym_braces,
      sym_command_substitution,
      sym_variable_substitution,
      aux_sym_arguments_list_repeat1,
  [141] = 8,
    ACTIONS(65), 1,
      anon_sym_SEMI,
    ACTIONS(67), 1,
      sym_bare_word,
    ACTIONS(70), 1,
      anon_sym_DQUOTE,
    ACTIONS(73), 1,
      anon_sym_LBRACE,
    ACTIONS(76), 1,
      anon_sym_LBRACK,
    ACTIONS(79), 1,
      anon_sym_DOLLAR,
    ACTIONS(63), 2,
      ts_builtin_sym_end,
      aux_sym__new_line_token1,
    STATE(6), 6,
      sym__word,
      sym_double_quotes,
      sym_braces,
      sym_command_substitution,
      sym_variable_substitution,
      aux_sym_arguments_list_repeat1,
  [172] = 8,
    ACTIONS(43), 1,
      anon_sym_DQUOTE,
    ACTIONS(45), 1,
      anon_sym_LBRACE,
    ACTIONS(47), 1,
      anon_sym_LBRACK,
    ACTIONS(49), 1,
      anon_sym_DOLLAR,
    ACTIONS(84), 1,
      anon_sym_SEMI,
    ACTIONS(86), 1,
      sym_bare_word,
    ACTIONS(82), 2,
      ts_builtin_sym_end,
      aux_sym__new_line_token1,
    STATE(6), 6,
      sym__word,
      sym_double_quotes,
      sym_braces,
      sym_command_substitution,
      sym_variable_substitution,
      aux_sym_arguments_list_repeat1,
  [203] = 8,
    ACTIONS(55), 1,
      anon_sym_DQUOTE,
    ACTIONS(57), 1,
      anon_sym_LBRACE,
    ACTIONS(59), 1,
      anon_sym_LBRACK,
    ACTIONS(61), 1,
      anon_sym_DOLLAR,
    ACTIONS(82), 1,
      aux_sym__new_line_token1,
    ACTIONS(84), 1,
      anon_sym_SEMI,
    ACTIONS(88), 1,
      sym_bare_word,
    STATE(9), 6,
      sym__word,
      sym_double_quotes,
      sym_braces,
      sym_command_substitution,
      sym_variable_substitution,
      aux_sym_arguments_list_repeat1,
  [233] = 8,
    ACTIONS(63), 1,
      aux_sym__new_line_token1,
    ACTIONS(65), 1,
      anon_sym_SEMI,
    ACTIONS(90), 1,
      sym_bare_word,
    ACTIONS(93), 1,
      anon_sym_DQUOTE,
    ACTIONS(96), 1,
      anon_sym_LBRACE,
    ACTIONS(99), 1,
      anon_sym_LBRACK,
    ACTIONS(102), 1,
      anon_sym_DOLLAR,
    STATE(9), 6,
      sym__word,
      sym_double_quotes,
      sym_braces,
      sym_command_substitution,
      sym_variable_substitution,
      aux_sym_arguments_list_repeat1,
  [263] = 8,
    ACTIONS(39), 1,
      anon_sym_RBRACK,
    ACTIONS(105), 1,
      sym_bare_word,
    ACTIONS(107), 1,
      anon_sym_DQUOTE,
    ACTIONS(109), 1,
      anon_sym_LBRACE,
    ACTIONS(111), 1,
      anon_sym_LBRACK,
    ACTIONS(113), 1,
      anon_sym_DOLLAR,
    STATE(109), 1,
      sym_arguments_list,
    STATE(12), 6,
      sym__word,
      sym_double_quotes,
      sym_braces,
      sym_command_substitution,
      sym_variable_substitution,
      aux_sym_arguments_list_repeat1,
  [293] = 7,
    ACTIONS(65), 1,
      anon_sym_RBRACK,
    ACTIONS(115), 1,
      sym_bare_word,
    ACTIONS(118), 1,
      anon_sym_DQUOTE,
    ACTIONS(121), 1,
      anon_sym_LBRACE,
    ACTIONS(124), 1,
      anon_sym_LBRACK,
    ACTIONS(127), 1,
      anon_sym_DOLLAR,
    STATE(11), 6,
      sym__word,
      sym_double_quotes,
      sym_braces,
      sym_command_substitution,
      sym_variable_substitution,
      aux_sym_arguments_list_repeat1,
  [320] = 7,
    ACTIONS(84), 1,
      anon_sym_RBRACK,
    ACTIONS(107), 1,
      anon_sym_DQUOTE,
    ACTIONS(109), 1,
      anon_sym_LBRACE,
    ACTIONS(111), 1,
      anon_sym_LBRACK,
    ACTIONS(113), 1,
      anon_sym_DOLLAR,
    ACTIONS(130), 1,
      sym_bare_word,
    STATE(11), 6,
      sym__word,
      sym_double_quotes,
      sym_braces,
      sym_command_substitution,
      sym_variable_substitution,
      aux_sym_arguments_list_repeat1,
  [347] = 7,
    ACTIONS(107), 1,
      anon_sym_DQUOTE,
    ACTIONS(109), 1,
      anon_sym_LBRACE,
    ACTIONS(111), 1,
      anon_sym_LBRACK,
    ACTIONS(113), 1,
      anon_sym_DOLLAR,
    ACTIONS(132), 1,
      sym_bare_word,
    STATE(93), 1,
      sym_command,
    STATE(10), 5,
      sym__word,
      sym_double_quotes,
      sym_braces,
      sym_command_substitution,
      sym_variable_substitution,
  [373] = 7,
    ACTIONS(107), 1,
      anon_sym_DQUOTE,
    ACTIONS(109), 1,
      anon_sym_LBRACE,
    ACTIONS(111), 1,
      anon_sym_LBRACK,
    ACTIONS(113), 1,
      anon_sym_DOLLAR,
    ACTIONS(132), 1,
      sym_bare_word,
    STATE(100), 1,
      sym_command,
    STATE(10), 5,
      sym__word,
      sym_double_quotes,
      sym_braces,
      sym_command_substitution,
      sym_variable_substitution,
  [399] = 7,
    ACTIONS(107), 1,
      anon_sym_DQUOTE,
    ACTIONS(109), 1,
      anon_sym_LBRACE,
    ACTIONS(111), 1,
      anon_sym_LBRACK,
    ACTIONS(113), 1,
      anon_sym_DOLLAR,
    ACTIONS(132), 1,
      sym_bare_word,
    STATE(95), 1,
      sym_command,
    STATE(10), 5,
      sym__word,
      sym_double_quotes,
      sym_braces,
      sym_command_substitution,
      sym_variable_substitution,
  [425] = 7,
    ACTIONS(107), 1,
      anon_sym_DQUOTE,
    ACTIONS(109), 1,
      anon_sym_LBRACE,
    ACTIONS(111), 1,
      anon_sym_LBRACK,
    ACTIONS(113), 1,
      anon_sym_DOLLAR,
    ACTIONS(132), 1,
      sym_bare_word,
    STATE(91), 1,
      sym_command,
    STATE(10), 5,
      sym__word,
      sym_double_quotes,
      sym_braces,
      sym_command_substitution,
      sym_variable_substitution,
  [451] = 7,
    ACTIONS(107), 1,
      anon_sym_DQUOTE,
    ACTIONS(109), 1,
      anon_sym_LBRACE,
    ACTIONS(111), 1,
      anon_sym_LBRACK,
    ACTIONS(113), 1,
      anon_sym_DOLLAR,
    ACTIONS(132), 1,
      sym_bare_word,
    STATE(102), 1,
      sym_command,
    STATE(10), 5,
      sym__word,
      sym_double_quotes,
      sym_braces,
      sym_command_substitution,
      sym_variable_substitution,
  [477] = 6,
    ACTIONS(134), 1,
      sym_bare_word,
    ACTIONS(136), 1,
      anon_sym_DQUOTE,
    ACTIONS(138), 1,
      anon_sym_LBRACE,
    ACTIONS(140), 1,
      anon_sym_LBRACK,
    ACTIONS(142), 1,
      anon_sym_DOLLAR,
    STATE(97), 5,
      sym__word,
      sym_double_quotes,
      sym_braces,
      sym_command_substitution,
      sym_variable_substitution,
  [500] = 6,
    ACTIONS(136), 1,
      anon_sym_DQUOTE,
    ACTIONS(138), 1,
      anon_sym_LBRACE,
    ACTIONS(140), 1,
      anon_sym_LBRACK,
    ACTIONS(142), 1,
      anon_sym_DOLLAR,
    ACTIONS(144), 1,
      sym_bare_word,
    STATE(101), 5,
      sym__word,
      sym_double_quotes,
      sym_braces,
      sym_command_substitution,
      sym_variable_substitution,
  [523] = 6,
    ACTIONS(136), 1,
      anon_sym_DQUOTE,
    ACTIONS(138), 1,
      anon_sym_LBRACE,
    ACTIONS(140), 1,
      anon_sym_LBRACK,
    ACTIONS(142), 1,
      anon_sym_DOLLAR,
    ACTIONS(146), 1,
      sym_bare_word,
    STATE(96), 5,
      sym__word,
      sym_double_quotes,
      sym_braces,
      sym_command_substitution,
      sym_variable_substitution,
  [546] = 6,
    ACTIONS(136), 1,
      anon_sym_DQUOTE,
    ACTIONS(138), 1,
      anon_sym_LBRACE,
    ACTIONS(140), 1,
      anon_sym_LBRACK,
    ACTIONS(142), 1,
      anon_sym_DOLLAR,
    ACTIONS(148), 1,
      sym_bare_word,
    STATE(98), 5,
      sym__word,
      sym_double_quotes,
      sym_braces,
      sym_command_substitution,
      sym_variable_substitution,
  [569] = 6,
    ACTIONS(136), 1,
      anon_sym_DQUOTE,
    ACTIONS(138), 1,
      anon_sym_LBRACE,
    ACTIONS(140), 1,
      anon_sym_LBRACK,
    ACTIONS(142), 1,
      anon_sym_DOLLAR,
    ACTIONS(150), 1,
      sym_bare_word,
    STATE(103), 5,
      sym__word,
      sym_double_quotes,
      sym_braces,
      sym_command_substitution,
      sym_variable_substitution,
  [592] = 6,
    ACTIONS(152), 1,
      anon_sym_DQUOTE,
    ACTIONS(154), 1,
      aux_sym__double_quotes_internal_token1,
    ACTIONS(156), 1,
      anon_sym_LBRACK,
    ACTIONS(158), 1,
      anon_sym_DOLLAR,
    ACTIONS(160), 1,
      anon_sym_BSLASH,
    STATE(29), 4,
      aux_sym__double_quotes_internal,
      sym_command_substitution,
      sym_variable_substitution,
      sym__backslash_substitution,
  [614] = 6,
    ACTIONS(156), 1,
      anon_sym_LBRACK,
    ACTIONS(158), 1,
      anon_sym_DOLLAR,
    ACTIONS(160), 1,
      anon_sym_BSLASH,
    ACTIONS(162), 1,
      anon_sym_DQUOTE,
    ACTIONS(164), 1,
      aux_sym__double_quotes_internal_token1,
    STATE(23), 4,
      aux_sym__double_quotes_internal,
      sym_command_substitution,
      sym_variable_substitution,
      sym__backslash_substitution,
  [636] = 3,
    ACTIONS(170), 1,
      anon_sym_LPAREN,
    ACTIONS(166), 2,
      ts_builtin_sym_end,
      aux_sym__new_line_token1,
    ACTIONS(168), 6,
      anon_sym_SEMI,
      sym_bare_word,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_DOLLAR,
  [652] = 6,
    ACTIONS(154), 1,
      aux_sym__double_quotes_internal_token1,
    ACTIONS(156), 1,
      anon_sym_LBRACK,
    ACTIONS(158), 1,
      anon_sym_DOLLAR,
    ACTIONS(160), 1,
      anon_sym_BSLASH,
    ACTIONS(172), 1,
      anon_sym_DQUOTE,
    STATE(29), 4,
      aux_sym__double_quotes_internal,
      sym_command_substitution,
      sym_variable_substitution,
      sym__backslash_substitution,
  [674] = 6,
    ACTIONS(156), 1,
      anon_sym_LBRACK,
    ACTIONS(158), 1,
      anon_sym_DOLLAR,
    ACTIONS(160), 1,
      anon_sym_BSLASH,
    ACTIONS(174), 1,
      anon_sym_DQUOTE,
    ACTIONS(176), 1,
      aux_sym__double_quotes_internal_token1,
    STATE(26), 4,
      aux_sym__double_quotes_internal,
      sym_command_substitution,
      sym_variable_substitution,
      sym__backslash_substitution,
  [696] = 6,
    ACTIONS(154), 1,
      aux_sym__double_quotes_internal_token1,
    ACTIONS(156), 1,
      anon_sym_LBRACK,
    ACTIONS(158), 1,
      anon_sym_DOLLAR,
    ACTIONS(160), 1,
      anon_sym_BSLASH,
    ACTIONS(178), 1,
      anon_sym_DQUOTE,
    STATE(29), 4,
      aux_sym__double_quotes_internal,
      sym_command_substitution,
      sym_variable_substitution,
      sym__backslash_substitution,
  [718] = 6,
    ACTIONS(180), 1,
      anon_sym_DQUOTE,
    ACTIONS(182), 1,
      aux_sym__double_quotes_internal_token1,
    ACTIONS(185), 1,
      anon_sym_LBRACK,
    ACTIONS(188), 1,
      anon_sym_DOLLAR,
    ACTIONS(191), 1,
      anon_sym_BSLASH,
    STATE(29), 4,
      aux_sym__double_quotes_internal,
      sym_command_substitution,
      sym_variable_substitution,
      sym__backslash_substitution,
  [740] = 6,
    ACTIONS(156), 1,
      anon_sym_LBRACK,
    ACTIONS(158), 1,
      anon_sym_DOLLAR,
    ACTIONS(160), 1,
      anon_sym_BSLASH,
    ACTIONS(194), 1,
      anon_sym_DQUOTE,
    ACTIONS(196), 1,
      aux_sym__double_quotes_internal_token1,
    STATE(28), 4,
      aux_sym__double_quotes_internal,
      sym_command_substitution,
      sym_variable_substitution,
      sym__backslash_substitution,
  [762] = 6,
    ACTIONS(154), 1,
      aux_sym__double_quotes_internal_token1,
    ACTIONS(156), 1,
      anon_sym_LBRACK,
    ACTIONS(158), 1,
      anon_sym_DOLLAR,
    ACTIONS(160), 1,
      anon_sym_BSLASH,
    ACTIONS(198), 1,
      anon_sym_DQUOTE,
    STATE(29), 4,
      aux_sym__double_quotes_internal,
      sym_command_substitution,
      sym_variable_substitution,
      sym__backslash_substitution,
  [784] = 6,
    ACTIONS(156), 1,
      anon_sym_LBRACK,
    ACTIONS(158), 1,
      anon_sym_DOLLAR,
    ACTIONS(160), 1,
      anon_sym_BSLASH,
    ACTIONS(200), 1,
      anon_sym_DQUOTE,
    ACTIONS(202), 1,
      aux_sym__double_quotes_internal_token1,
    STATE(31), 4,
      aux_sym__double_quotes_internal,
      sym_command_substitution,
      sym_variable_substitution,
      sym__backslash_substitution,
  [806] = 2,
    ACTIONS(204), 2,
      ts_builtin_sym_end,
      aux_sym__new_line_token1,
    ACTIONS(206), 6,
      anon_sym_SEMI,
      sym_bare_word,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_DOLLAR,
  [819] = 2,
    ACTIONS(208), 2,
      ts_builtin_sym_end,
      aux_sym__new_line_token1,
    ACTIONS(210), 6,
      anon_sym_SEMI,
      sym_bare_word,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_DOLLAR,
  [832] = 2,
    ACTIONS(212), 2,
      ts_builtin_sym_end,
      aux_sym__new_line_token1,
    ACTIONS(214), 6,
      anon_sym_SEMI,
      sym_bare_word,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_DOLLAR,
  [845] = 2,
    ACTIONS(216), 2,
      ts_builtin_sym_end,
      aux_sym__new_line_token1,
    ACTIONS(218), 6,
      anon_sym_SEMI,
      sym_bare_word,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_DOLLAR,
  [858] = 3,
    ACTIONS(166), 1,
      aux_sym__new_line_token1,
    ACTIONS(220), 1,
      anon_sym_LPAREN,
    ACTIONS(168), 6,
      anon_sym_SEMI,
      sym_bare_word,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_DOLLAR,
  [873] = 2,
    ACTIONS(166), 2,
      ts_builtin_sym_end,
      aux_sym__new_line_token1,
    ACTIONS(168), 6,
      anon_sym_SEMI,
      sym_bare_word,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_DOLLAR,
  [886] = 2,
    ACTIONS(222), 2,
      ts_builtin_sym_end,
      aux_sym__new_line_token1,
    ACTIONS(224), 6,
      anon_sym_SEMI,
      sym_bare_word,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_DOLLAR,
  [899] = 2,
    ACTIONS(226), 2,
      ts_builtin_sym_end,
      aux_sym__new_line_token1,
    ACTIONS(228), 6,
      anon_sym_SEMI,
      sym_bare_word,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_DOLLAR,
  [912] = 2,
    ACTIONS(204), 1,
      aux_sym__new_line_token1,
    ACTIONS(206), 6,
      anon_sym_SEMI,
      sym_bare_word,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_DOLLAR,
  [924] = 2,
    ACTIONS(208), 1,
      aux_sym__new_line_token1,
    ACTIONS(210), 6,
      anon_sym_SEMI,
      sym_bare_word,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_DOLLAR,
  [936] = 2,
    ACTIONS(166), 1,
      aux_sym__new_line_token1,
    ACTIONS(168), 6,
      anon_sym_SEMI,
      sym_bare_word,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_DOLLAR,
  [948] = 2,
    ACTIONS(216), 1,
      aux_sym__new_line_token1,
    ACTIONS(218), 6,
      anon_sym_SEMI,
      sym_bare_word,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_DOLLAR,
  [960] = 2,
    ACTIONS(226), 1,
      aux_sym__new_line_token1,
    ACTIONS(228), 6,
      anon_sym_SEMI,
      sym_bare_word,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_DOLLAR,
  [972] = 3,
    ACTIONS(230), 1,
      anon_sym_LPAREN,
    ACTIONS(168), 2,
      sym_bare_word,
      anon_sym_RBRACK,
    ACTIONS(166), 4,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_DOLLAR,
  [986] = 2,
    ACTIONS(212), 1,
      aux_sym__new_line_token1,
    ACTIONS(214), 6,
      anon_sym_SEMI,
      sym_bare_word,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_DOLLAR,
  [998] = 2,
    ACTIONS(222), 1,
      aux_sym__new_line_token1,
    ACTIONS(224), 6,
      anon_sym_SEMI,
      sym_bare_word,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_DOLLAR,
  [1010] = 2,
    ACTIONS(232), 2,
      sym_bare_word,
      aux_sym_comment_token1,
    ACTIONS(17), 5,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_DOLLAR,
  [1022] = 2,
    ACTIONS(168), 2,
      sym_bare_word,
      anon_sym_RBRACK,
    ACTIONS(166), 4,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_DOLLAR,
  [1033] = 2,
    ACTIONS(234), 1,
      anon_sym_LPAREN,
    ACTIONS(168), 5,
      anon_sym_DQUOTE,
      aux_sym__double_quotes_internal_token1,
      anon_sym_LBRACK,
      anon_sym_DOLLAR,
      anon_sym_BSLASH,
  [1044] = 2,
    ACTIONS(210), 2,
      sym_bare_word,
      anon_sym_RBRACK,
    ACTIONS(208), 4,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_DOLLAR,
  [1055] = 2,
    ACTIONS(228), 2,
      sym_bare_word,
      anon_sym_RBRACK,
    ACTIONS(226), 4,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_DOLLAR,
  [1066] = 2,
    ACTIONS(206), 2,
      sym_bare_word,
      anon_sym_RBRACK,
    ACTIONS(204), 4,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_DOLLAR,
  [1077] = 2,
    ACTIONS(218), 2,
      sym_bare_word,
      anon_sym_RBRACK,
    ACTIONS(216), 4,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_DOLLAR,
  [1088] = 2,
    ACTIONS(214), 2,
      sym_bare_word,
      anon_sym_RBRACK,
    ACTIONS(212), 4,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_DOLLAR,
  [1099] = 2,
    ACTIONS(224), 2,
      sym_bare_word,
      anon_sym_RBRACK,
    ACTIONS(222), 4,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_DOLLAR,
  [1110] = 2,
    ACTIONS(208), 1,
      aux_sym__double_quotes_internal_token1,
    ACTIONS(210), 4,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_DOLLAR,
      anon_sym_BSLASH,
  [1120] = 4,
    ACTIONS(236), 1,
      anon_sym_LBRACE,
    ACTIONS(239), 1,
      anon_sym_RBRACE,
    ACTIONS(241), 1,
      aux_sym__braces_internal_token1,
    STATE(59), 2,
      aux_sym__braces_internal,
      sym__even_braces,
  [1134] = 2,
    ACTIONS(216), 1,
      aux_sym__double_quotes_internal_token1,
    ACTIONS(218), 4,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_DOLLAR,
      anon_sym_BSLASH,
  [1144] = 4,
    ACTIONS(244), 1,
      anon_sym_LBRACE,
    ACTIONS(246), 1,
      anon_sym_RBRACE,
    ACTIONS(248), 1,
      aux_sym__braces_internal_token1,
    STATE(67), 2,
      aux_sym__braces_internal,
      sym__even_braces,
  [1158] = 4,
    ACTIONS(51), 1,
      ts_builtin_sym_end,
    ACTIONS(250), 1,
      anon_sym_SEMI,
    ACTIONS(252), 1,
      aux_sym__new_line_token1,
    STATE(49), 2,
      sym__terminator,
      sym__new_line,
  [1172] = 4,
    ACTIONS(244), 1,
      anon_sym_LBRACE,
    ACTIONS(254), 1,
      anon_sym_RBRACE,
    ACTIONS(256), 1,
      aux_sym__braces_internal_token1,
    STATE(59), 2,
      aux_sym__braces_internal,
      sym__even_braces,
  [1186] = 2,
    ACTIONS(166), 1,
      aux_sym__double_quotes_internal_token1,
    ACTIONS(168), 4,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_DOLLAR,
      anon_sym_BSLASH,
  [1196] = 2,
    ACTIONS(260), 1,
      aux_sym__double_quotes_internal_token1,
    ACTIONS(258), 4,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_DOLLAR,
      anon_sym_BSLASH,
  [1206] = 4,
    ACTIONS(244), 1,
      anon_sym_LBRACE,
    ACTIONS(262), 1,
      anon_sym_RBRACE,
    ACTIONS(264), 1,
      aux_sym__braces_internal_token1,
    STATE(76), 2,
      aux_sym__braces_internal,
      sym__even_braces,
  [1220] = 4,
    ACTIONS(244), 1,
      anon_sym_LBRACE,
    ACTIONS(256), 1,
      aux_sym__braces_internal_token1,
    ACTIONS(266), 1,
      anon_sym_RBRACE,
    STATE(59), 2,
      aux_sym__braces_internal,
      sym__even_braces,
  [1234] = 4,
    ACTIONS(244), 1,
      anon_sym_LBRACE,
    ACTIONS(256), 1,
      aux_sym__braces_internal_token1,
    ACTIONS(268), 1,
      anon_sym_RBRACE,
    STATE(59), 2,
      aux_sym__braces_internal,
      sym__even_braces,
  [1248] = 2,
    ACTIONS(212), 1,
      aux_sym__double_quotes_internal_token1,
    ACTIONS(214), 4,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_DOLLAR,
      anon_sym_BSLASH,
  [1258] = 4,
    ACTIONS(244), 1,
      anon_sym_LBRACE,
    ACTIONS(270), 1,
      anon_sym_RBRACE,
    ACTIONS(272), 1,
      aux_sym__braces_internal_token1,
    STATE(68), 2,
      aux_sym__braces_internal,
      sym__even_braces,
  [1272] = 4,
    ACTIONS(244), 1,
      anon_sym_LBRACE,
    ACTIONS(256), 1,
      aux_sym__braces_internal_token1,
    ACTIONS(274), 1,
      anon_sym_RBRACE,
    STATE(59), 2,
      aux_sym__braces_internal,
      sym__even_braces,
  [1286] = 4,
    ACTIONS(244), 1,
      anon_sym_LBRACE,
    ACTIONS(276), 1,
      anon_sym_RBRACE,
    ACTIONS(278), 1,
      aux_sym__braces_internal_token1,
    STATE(71), 2,
      aux_sym__braces_internal,
      sym__even_braces,
  [1300] = 4,
    ACTIONS(244), 1,
      anon_sym_LBRACE,
    ACTIONS(256), 1,
      aux_sym__braces_internal_token1,
    ACTIONS(280), 1,
      anon_sym_RBRACE,
    STATE(59), 2,
      aux_sym__braces_internal,
      sym__even_braces,
  [1314] = 4,
    ACTIONS(250), 1,
      anon_sym_SEMI,
    ACTIONS(252), 1,
      aux_sym__new_line_token1,
    ACTIONS(282), 1,
      ts_builtin_sym_end,
    STATE(49), 2,
      sym__terminator,
      sym__new_line,
  [1328] = 4,
    ACTIONS(244), 1,
      anon_sym_LBRACE,
    ACTIONS(284), 1,
      anon_sym_RBRACE,
    ACTIONS(286), 1,
      aux_sym__braces_internal_token1,
    STATE(73), 2,
      aux_sym__braces_internal,
      sym__even_braces,
  [1342] = 4,
    ACTIONS(244), 1,
      anon_sym_LBRACE,
    ACTIONS(256), 1,
      aux_sym__braces_internal_token1,
    ACTIONS(288), 1,
      anon_sym_RBRACE,
    STATE(59), 2,
      aux_sym__braces_internal,
      sym__even_braces,
  [1356] = 4,
    ACTIONS(244), 1,
      anon_sym_LBRACE,
    ACTIONS(290), 1,
      anon_sym_RBRACE,
    ACTIONS(292), 1,
      aux_sym__braces_internal_token1,
    STATE(63), 2,
      aux_sym__braces_internal,
      sym__even_braces,
  [1370] = 2,
    ACTIONS(204), 1,
      aux_sym__double_quotes_internal_token1,
    ACTIONS(206), 4,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_DOLLAR,
      anon_sym_BSLASH,
  [1380] = 3,
    ACTIONS(250), 1,
      anon_sym_SEMI,
    ACTIONS(252), 1,
      aux_sym__new_line_token1,
    STATE(49), 2,
      sym__terminator,
      sym__new_line,
  [1391] = 3,
    ACTIONS(294), 1,
      anon_sym_LBRACE,
    ACTIONS(296), 1,
      sym_alowed_variable_name,
    STATE(64), 1,
      sym_braces,
  [1401] = 3,
    ACTIONS(298), 1,
      anon_sym_LBRACE,
    ACTIONS(300), 1,
      sym_alowed_variable_name,
    STATE(43), 1,
      sym_braces,
  [1411] = 3,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(302), 1,
      sym_alowed_variable_name,
    STATE(38), 1,
      sym_braces,
  [1421] = 2,
    ACTIONS(306), 1,
      aux_sym__braces_internal_token1,
    ACTIONS(304), 2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1429] = 3,
    ACTIONS(109), 1,
      anon_sym_LBRACE,
    ACTIONS(308), 1,
      sym_alowed_variable_name,
    STATE(50), 1,
      sym_braces,
  [1439] = 2,
    ACTIONS(312), 1,
      aux_sym__braces_internal_token1,
    ACTIONS(310), 2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1447] = 3,
    ACTIONS(138), 1,
      anon_sym_LBRACE,
    ACTIONS(314), 1,
      sym_alowed_variable_name,
    STATE(94), 1,
      sym_braces,
  [1457] = 2,
    ACTIONS(318), 1,
      anon_sym_SEMI,
    ACTIONS(316), 2,
      ts_builtin_sym_end,
      aux_sym__new_line_token1,
  [1465] = 2,
    ACTIONS(320), 1,
      anon_sym_SEMI,
    ACTIONS(322), 1,
      aux_sym__new_line_token1,
  [1472] = 1,
    ACTIONS(324), 2,
      aux_sym__new_line_token1,
      aux_sym__backslash_substitution_token1,
  [1477] = 2,
    ACTIONS(166), 1,
      anon_sym_RPAREN,
    ACTIONS(326), 1,
      anon_sym_LPAREN,
  [1484] = 1,
    ACTIONS(328), 1,
      anon_sym_RBRACK,
  [1488] = 1,
    ACTIONS(208), 1,
      anon_sym_RPAREN,
  [1492] = 1,
    ACTIONS(330), 1,
      anon_sym_RBRACK,
  [1496] = 1,
    ACTIONS(166), 1,
      anon_sym_RPAREN,
  [1500] = 1,
    ACTIONS(332), 1,
      anon_sym_RBRACK,
  [1504] = 1,
    ACTIONS(334), 1,
      anon_sym_RPAREN,
  [1508] = 1,
    ACTIONS(336), 1,
      anon_sym_RPAREN,
  [1512] = 1,
    ACTIONS(338), 1,
      anon_sym_RPAREN,
  [1516] = 1,
    ACTIONS(216), 1,
      anon_sym_RPAREN,
  [1520] = 1,
    ACTIONS(340), 1,
      anon_sym_RBRACK,
  [1524] = 1,
    ACTIONS(342), 1,
      anon_sym_RPAREN,
  [1528] = 1,
    ACTIONS(344), 1,
      anon_sym_RBRACK,
  [1532] = 1,
    ACTIONS(346), 1,
      anon_sym_RPAREN,
  [1536] = 1,
    ACTIONS(204), 1,
      anon_sym_RPAREN,
  [1540] = 1,
    ACTIONS(226), 1,
      anon_sym_RPAREN,
  [1544] = 1,
    ACTIONS(222), 1,
      anon_sym_RPAREN,
  [1548] = 1,
    ACTIONS(348), 1,
      ts_builtin_sym_end,
  [1552] = 1,
    ACTIONS(212), 1,
      anon_sym_RPAREN,
  [1556] = 1,
    ACTIONS(316), 1,
      anon_sym_RBRACK,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 36,
  [SMALL_STATE(4)] = 70,
  [SMALL_STATE(5)] = 108,
  [SMALL_STATE(6)] = 141,
  [SMALL_STATE(7)] = 172,
  [SMALL_STATE(8)] = 203,
  [SMALL_STATE(9)] = 233,
  [SMALL_STATE(10)] = 263,
  [SMALL_STATE(11)] = 293,
  [SMALL_STATE(12)] = 320,
  [SMALL_STATE(13)] = 347,
  [SMALL_STATE(14)] = 373,
  [SMALL_STATE(15)] = 399,
  [SMALL_STATE(16)] = 425,
  [SMALL_STATE(17)] = 451,
  [SMALL_STATE(18)] = 477,
  [SMALL_STATE(19)] = 500,
  [SMALL_STATE(20)] = 523,
  [SMALL_STATE(21)] = 546,
  [SMALL_STATE(22)] = 569,
  [SMALL_STATE(23)] = 592,
  [SMALL_STATE(24)] = 614,
  [SMALL_STATE(25)] = 636,
  [SMALL_STATE(26)] = 652,
  [SMALL_STATE(27)] = 674,
  [SMALL_STATE(28)] = 696,
  [SMALL_STATE(29)] = 718,
  [SMALL_STATE(30)] = 740,
  [SMALL_STATE(31)] = 762,
  [SMALL_STATE(32)] = 784,
  [SMALL_STATE(33)] = 806,
  [SMALL_STATE(34)] = 819,
  [SMALL_STATE(35)] = 832,
  [SMALL_STATE(36)] = 845,
  [SMALL_STATE(37)] = 858,
  [SMALL_STATE(38)] = 873,
  [SMALL_STATE(39)] = 886,
  [SMALL_STATE(40)] = 899,
  [SMALL_STATE(41)] = 912,
  [SMALL_STATE(42)] = 924,
  [SMALL_STATE(43)] = 936,
  [SMALL_STATE(44)] = 948,
  [SMALL_STATE(45)] = 960,
  [SMALL_STATE(46)] = 972,
  [SMALL_STATE(47)] = 986,
  [SMALL_STATE(48)] = 998,
  [SMALL_STATE(49)] = 1010,
  [SMALL_STATE(50)] = 1022,
  [SMALL_STATE(51)] = 1033,
  [SMALL_STATE(52)] = 1044,
  [SMALL_STATE(53)] = 1055,
  [SMALL_STATE(54)] = 1066,
  [SMALL_STATE(55)] = 1077,
  [SMALL_STATE(56)] = 1088,
  [SMALL_STATE(57)] = 1099,
  [SMALL_STATE(58)] = 1110,
  [SMALL_STATE(59)] = 1120,
  [SMALL_STATE(60)] = 1134,
  [SMALL_STATE(61)] = 1144,
  [SMALL_STATE(62)] = 1158,
  [SMALL_STATE(63)] = 1172,
  [SMALL_STATE(64)] = 1186,
  [SMALL_STATE(65)] = 1196,
  [SMALL_STATE(66)] = 1206,
  [SMALL_STATE(67)] = 1220,
  [SMALL_STATE(68)] = 1234,
  [SMALL_STATE(69)] = 1248,
  [SMALL_STATE(70)] = 1258,
  [SMALL_STATE(71)] = 1272,
  [SMALL_STATE(72)] = 1286,
  [SMALL_STATE(73)] = 1300,
  [SMALL_STATE(74)] = 1314,
  [SMALL_STATE(75)] = 1328,
  [SMALL_STATE(76)] = 1342,
  [SMALL_STATE(77)] = 1356,
  [SMALL_STATE(78)] = 1370,
  [SMALL_STATE(79)] = 1380,
  [SMALL_STATE(80)] = 1391,
  [SMALL_STATE(81)] = 1401,
  [SMALL_STATE(82)] = 1411,
  [SMALL_STATE(83)] = 1421,
  [SMALL_STATE(84)] = 1429,
  [SMALL_STATE(85)] = 1439,
  [SMALL_STATE(86)] = 1447,
  [SMALL_STATE(87)] = 1457,
  [SMALL_STATE(88)] = 1465,
  [SMALL_STATE(89)] = 1472,
  [SMALL_STATE(90)] = 1477,
  [SMALL_STATE(91)] = 1484,
  [SMALL_STATE(92)] = 1488,
  [SMALL_STATE(93)] = 1492,
  [SMALL_STATE(94)] = 1496,
  [SMALL_STATE(95)] = 1500,
  [SMALL_STATE(96)] = 1504,
  [SMALL_STATE(97)] = 1508,
  [SMALL_STATE(98)] = 1512,
  [SMALL_STATE(99)] = 1516,
  [SMALL_STATE(100)] = 1520,
  [SMALL_STATE(101)] = 1524,
  [SMALL_STATE(102)] = 1528,
  [SMALL_STATE(103)] = 1532,
  [SMALL_STATE(104)] = 1536,
  [SMALL_STATE(105)] = 1540,
  [SMALL_STATE(106)] = 1544,
  [SMALL_STATE(107)] = 1548,
  [SMALL_STATE(108)] = 1552,
  [SMALL_STATE(109)] = 1556,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tcl_script, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(88),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tcl_script_repeat1, 2),
  [19] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_tcl_script_repeat1, 2), SHIFT_REPEAT(5),
  [22] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tcl_script_repeat1, 2), SHIFT_REPEAT(27),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tcl_script_repeat1, 2), SHIFT_REPEAT(72),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tcl_script_repeat1, 2), SHIFT_REPEAT(15),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tcl_script_repeat1, 2), SHIFT_REPEAT(81),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_tcl_script_repeat1, 2), SHIFT_REPEAT(88),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 1, .production_id = 1),
  [39] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command, 1, .production_id = 1),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tcl_script, 1),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_arguments_list_repeat1, 2),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_arguments_list_repeat1, 2),
  [67] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_arguments_list_repeat1, 2), SHIFT_REPEAT(6),
  [70] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_arguments_list_repeat1, 2), SHIFT_REPEAT(32),
  [73] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_arguments_list_repeat1, 2), SHIFT_REPEAT(61),
  [76] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_arguments_list_repeat1, 2), SHIFT_REPEAT(13),
  [79] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_arguments_list_repeat1, 2), SHIFT_REPEAT(82),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments_list, 1),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arguments_list, 1),
  [86] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [88] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [90] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_arguments_list_repeat1, 2), SHIFT_REPEAT(9),
  [93] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_arguments_list_repeat1, 2), SHIFT_REPEAT(27),
  [96] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_arguments_list_repeat1, 2), SHIFT_REPEAT(72),
  [99] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_arguments_list_repeat1, 2), SHIFT_REPEAT(15),
  [102] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_arguments_list_repeat1, 2), SHIFT_REPEAT(81),
  [105] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [115] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_arguments_list_repeat1, 2), SHIFT_REPEAT(11),
  [118] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_arguments_list_repeat1, 2), SHIFT_REPEAT(30),
  [121] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_arguments_list_repeat1, 2), SHIFT_REPEAT(77),
  [124] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_arguments_list_repeat1, 2), SHIFT_REPEAT(16),
  [127] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_arguments_list_repeat1, 2), SHIFT_REPEAT(84),
  [130] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [152] = {.entry = {.count = 1, .reusable = false}}, SHIFT(105),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [156] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [158] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [160] = {.entry = {.count = 1, .reusable = false}}, SHIFT(89),
  [162] = {.entry = {.count = 1, .reusable = false}}, SHIFT(106),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_substitution, 2),
  [168] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_substitution, 2),
  [170] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [172] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [174] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [178] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [180] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__double_quotes_internal, 2),
  [182] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__double_quotes_internal, 2), SHIFT_REPEAT(29),
  [185] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__double_quotes_internal, 2), SHIFT_REPEAT(17),
  [188] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__double_quotes_internal, 2), SHIFT_REPEAT(80),
  [191] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__double_quotes_internal, 2), SHIFT_REPEAT(89),
  [194] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [198] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [200] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command_substitution, 3),
  [206] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command_substitution, 3),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_braces, 3),
  [210] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_braces, 3),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_substitution, 5),
  [214] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_substitution, 5),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_braces, 2),
  [218] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_braces, 2),
  [220] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_double_quotes, 2),
  [224] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_double_quotes, 2),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_double_quotes, 3),
  [228] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_double_quotes, 3),
  [230] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [232] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_tcl_script_repeat1, 2),
  [234] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [236] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__braces_internal, 2), SHIFT_REPEAT(66),
  [239] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__braces_internal, 2),
  [241] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__braces_internal, 2), SHIFT_REPEAT(59),
  [244] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [246] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [250] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [254] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [258] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__backslash_substitution, 2),
  [260] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__backslash_substitution, 2),
  [262] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [266] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [268] = {.entry = {.count = 1, .reusable = false}}, SHIFT(92),
  [270] = {.entry = {.count = 1, .reusable = false}}, SHIFT(99),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [274] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [276] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [280] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [282] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tcl_script, 2),
  [284] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [288] = {.entry = {.count = 1, .reusable = false}}, SHIFT(85),
  [290] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [304] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__even_braces, 2),
  [306] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__even_braces, 2),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [310] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__even_braces, 3),
  [312] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__even_braces, 3),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [316] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 2, .production_id = 2),
  [318] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command, 2, .production_id = 2),
  [320] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 1),
  [322] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 1),
  [324] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [328] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [330] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [332] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [334] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [336] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [338] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [340] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [342] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [344] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [346] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [348] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_tcl(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
